In [11]:
import numpy as np

#状態価値関数をランダムに初期化
V=np.random.rand(4,1)*10
print('V')
print(V)

#状態遷移行列
Pas=np.array([[0.9, 0.1,0,0],[0.1,0.9,0,0],[0.9,0.1,0,0],[0,0.1,0.9,0],
            [0,0.9,0.1,0],[0,0,0.1,0.9],[0,0,0.9,0.1],[0,0,0.1,0.9]])
print('Pas')
print(Pas)

#報酬ベクトル (状態がS4の時のみ報酬)
#推移確率行列にRを書けた数値が報酬の期待値
Rs=np.array([0,0,0,1])

#割引率
gamma=0.9

theta=0.000000001


V
[[ 1.23533615]
 [ 7.26992138]
 [ 1.76321833]
 [ 5.85072243]]
Pas
[[ 0.9  0.1  0.   0. ]
 [ 0.1  0.9  0.   0. ]
 [ 0.9  0.1  0.   0. ]
 [ 0.   0.1  0.9  0. ]
 [ 0.   0.9  0.1  0. ]
 [ 0.   0.   0.1  0.9]
 [ 0.   0.   0.9  0.1]
 [ 0.   0.   0.1  0.9]]


In [12]:
t=1
while True:
    print('time step ' + str(t))
    delta=0
    Vnext=Rs.reshape(4,1)+gamma*V #4次元の列ベクトル
    Q=np.dot(Pas,Vnext).reshape(4,2) #状態・行動価値関数
    print('Q')
    print(Q)
    Vupdate=Q.max(1).reshape(4,1) #各状態で最適行動を選ぶときの状態価値関数
    delta=max(np.absolute(Vupdate-V))
    V=Vupdate
    print('V')
    print(V)
    t+=1
    if delta<theta or t>10000:
        break
        
print('Optimal policy')
print(Q.argmax(1))

time step 1
Q
[[ 1.65491521  5.99981657]
 [ 1.65491521  2.08249977]
 [ 6.04732597  5.79777481]
 [ 2.05477187  5.79777481]]
V
[[ 5.99981657]
 [ 2.08249977]
 [ 6.04732597]
 [ 5.79777481]]
time step 2
Q
[[ 5.0472764   2.22680831]
 [ 5.0472764   5.08575901]
 [ 2.23108415  6.14045694]
 [ 5.52013377  6.14045694]]
V
[[ 5.0472764 ]
 [ 5.08575901]
 [ 6.14045694]
 [ 6.14045694]]
time step 3
Q
[[ 4.5460122   4.57371968]
 [ 4.5460122   5.43148843]
 [ 4.67210593  6.42641124]
 [ 5.62641124  6.42641124]]
V
[[ 4.57371968]
 [ 5.43148843]
 [ 6.42641124]
 [ 6.42641124]]
time step 4
Q
[[ 4.1935469   4.8111404 ]
 [ 4.1935469   5.69422707]
 [ 4.97788264  6.68377012]
 [ 5.88377012  6.68377012]]
V
[[ 4.8111404 ]
 [ 5.69422707]
 [ 6.68377012]
 [ 6.68377012]]
time step 5
Q
[[ 4.40950416  5.04532656]
 [ 4.40950416  5.92633423]
 [ 5.21386323  6.91539311]
 [ 6.11539311  6.91539311]]
V
[[ 5.04532656]
 [ 5.92633423]
 [ 6.91539311]
 [ 6.91539311]]
time step 6
Q
[[ 4.62008459  5.25441012]
 [ 4.62008459  6.1348385 ]
 [