In [1]:
import numpy as np

#初期方策、状態価値関数をランダムに初期化
pL=np.random.rand(4)
print('pL')
print(pL)

V=np.random.rand(4,1)*10
print('V')
print(V)

#状態遷移行列
Pas=np.array([[0.9, 0.1,0,0],[0.1,0.9,0,0],[0.9,0.1,0,0],[0,0.1,0.9,0],
            [0,0.9,0.1,0],[0,0,0.1,0.9],[0,0,0.9,0.1],[0,0,0.1,0.9]])
print('Pas')
print(Pas)

pi=np.zeros(32).reshape(4,8)
for i in range(4):
    pi[i,2*i]=pL[i]
    pi[i,2*i+1]=1-pL[i]

print('pi')    
print(pi)

Maa = np.dot(Pas,pi)
print('Maa')
print(Maa)

#報酬ベクトル (状態がS4の時のみ報酬)
#推移確率行列にRを書けた数値が報酬の期待値
Ra=np.array([0,0,0,0,0,0,1,1])
Rs=np.array([0,0,0,1])

#割引率
gamma=0.9

theta=0.000000001




pL
[ 0.93051671  0.51014544  0.29372478  0.05598683]
V
[[ 7.42409068]
 [ 9.41687901]
 [ 8.0630064 ]
 [ 2.9097162 ]]
Pas
[[ 0.9  0.1  0.   0. ]
 [ 0.1  0.9  0.   0. ]
 [ 0.9  0.1  0.   0. ]
 [ 0.   0.1  0.9  0. ]
 [ 0.   0.9  0.1  0. ]
 [ 0.   0.   0.1  0.9]
 [ 0.   0.   0.9  0.1]
 [ 0.   0.   0.1  0.9]]
pi
[[ 0.93051671  0.06948329  0.          0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.51014544  0.48985456  0.          0.          0.
   0.        ]
 [ 0.          0.          0.          0.          0.29372478  0.70627522
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.05598683  0.94401317]]
Maa
[[ 0.83746504  0.06253496  0.05101454  0.04898546  0.          0.          0.
   0.        ]
 [ 0.09305167  0.00694833  0.4591309   0.4408691   0.          0.          0.
   0.        ]
 [ 0.83746504  0.06253496  0.05101454  0.04898546  0.          0.          0.
   0.        ]
 [ 0.          0.          0

In [3]:
t=1
while True:
    print('time step ' + str(t))
          
    ###方策評価###

    Mss=np.dot(pi,Pas)
    delta=theta
    i=0

    while(delta>=theta and i<100000):
        Vnext=Rs.reshape(4,1)+gamma*V #4次元の列ベクトル
        Vupdate=np.dot(Mss,Vnext) #価値関数の更新：状態遷移行列を前からかける
        delta=max(np.absolute(Vupdate-V))
        V=Vupdate
        i=i+1

    print('iteration')
    print(i)
    print('V')
    print(V)
    
    ###方策改善###
    Q=np.dot(Pas, Rs.reshape(4,1)+gamma*V).reshape(4,2)
    am=Q.argmax(1)
    print('argmax')
    print(am)
    
    b=pi

    #方策PiをGreedyに更新
    pi=np.zeros(32).reshape(4,8)
    for i in range(4):
        if am[i]==0: #Qが最大になるのがLの時,決定的にLを選択
            pi[i,2*i]=1
            pi[i,2*i+1]=0
        else: #Qが最大になるのがRの時,決定的にRを選択
            pi[i,2*i]=0
            pi[i,2*i+1]=1
    print('pi')
    print(pi)
    
    if np.allclose(pi,b): #一致判定
        break

    t+=1

time step 1
iteration
1
V
[[ 2.14523952]
 [ 3.67724744]
 [ 6.19948184]
 [ 7.22098252]]
argmax
[1 1 1 1]
pi
[[ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
time step 2
iteration
182
V
[[ 7.13066054]
 [ 8.010989  ]
 [ 8.99999999]
 [ 8.99999999]]
argmax
[1 1 1 1]
pi
[[ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
